### ISSUE TITLE
Change document_url to list

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.aleph_link_export#12]

**Comment by jstavel** [comment]
Hi Jaroslav.
Is it possible to send a description per each link?

**Comment by jstavel** [comment]
the same should be for kramerius_url. I guess.

**Comment by Bystroushaak** [comment]
Sorry, no description. AFAIK description is not the part of the record, but the Web template in Aleph. I've talked with Radek about the description and he said he would create _some solution_.

**Comment by Bystroushaak** [comment]
Kramerius link should be only one, shouldn't it? It makes no sense to generate three equivalent contents for kramerius.

**Comment by jstavel** [comment]
Hm. I would like to talk with you about it.

**Comment by Bystroushaak** [comment]
Lets hang out.

**Comment by jstavel** [comment]
I have sent a link to you.
