### ISSUE TITLE
Make sure that Radek will accept our XSD proposal

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.aleph_link_export#2]

**Comment by Bystroushaak** [comment]
I did sent him the link to the documentation and other informations.

**Comment by Bystroushaak** [comment]
I've talked with radek, he has the script almost ready.

**Comment by Bystroushaak** [comment]
I've added his SSH key to our servers.

**Comment by jstavel** [comment]
That is great!
I am waiting for mr. Bilwachs to open ssh port.

**Comment by jstavel** [comment]
(blocks edeposit/edeposit#575)

**Comment by jstavel** [comment]
eDeposit uz dostal odpovedi z alephu. nektere maji status='OK' jine maji 'Error' plus reason. Reason obsahuje dobre pochopitelnou hlasku.

Muzeme uzavrit?

**Comment by Bystroushaak** [comment]
Ok, uzavírám :)
