### ISSUE TITLE
What payload should be at tick message?

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.aleph_link_export#9]
Hi Jaroslav,
I have solved the problem with RabbitMQ Dos.
The problem was with type of exchange "update-links". The type was "fanout". It is one of simple types of exchange. Exchange of this type cannot dispatch messages by routing_key.
So that is it.

I changed a type of exchange "update-links" to "topic". And everything works well now.

**Comment by jstavel** [comment]
aleph_link_exportd need some proper payload sent in a message.

Please, give me an example of message for tick message.

Thanks,
Jan

**Comment by Bystroushaak** [comment]
It shoudln't require any payload, just StatusRequest() namedtuple. If the payload is required, I can add some constant into it, so it wouldn't be without value.

**Comment by jstavel** [comment]
Yes. Thank you. I will prepare it. Thanks.
